excluded:
 - 'build/*'
 - '**/ruby/*'
opt_in_rules:
 - all
disabled_rules:
 - required_deinit
 - type_contents_order
 - force_unwrapping
 - file_name
 - explicit_type_interface
 - no_magic_numbers
 - explicit_acl
 - explicit_top_level_acl
 - unavailable_function
 - conditional_returns_on_newline
 - fatal_error_message
 - implicitly_unwrapped_optional
 - closure_body_length
 - accessibility_trait_for_button
 - accessibility_label_for_image
 - prefer_nimble
 - anyobject_protocol
 - inert_defer
 - unused_capture_list
