# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Swiftlint
      run: swiftlint lint --strict

  test:
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Update XCBeautify
      run: brew install xcbeautify
    - name: Test CreateMLDemo
      run: set -o pipefail && xcodebuild clean build test -scheme "CreateMLDemo" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify --report junit --junit-report-filename createmldemo_junit_report.xml
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: createmldemo_junit_report.xml
    
