# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Swiftlint
      run: swiftlint lint --strict

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update XCBeautify
      run: brew install xcbeautify
    - name: Build CreateMLDemo
      run: set -o pipefail && xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update XCBeautify
      run: brew install xcbeautify
    - name: Test CreateMLDemo
      run: set -o pipefail && xcodebuild clean build test -scheme "CreateMLDemo" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify
    
