# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: macOS validate & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up ruby env
      uses: ruby/setup-ruby@v1.138.0
      with:
        ruby-version: 3.3.0
        bundler-cache: true

    - name: Swiftlint
      run: bundle exec fastlane lint

  unit_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up ruby env
      uses: ruby/setup-ruby@v1.138.0
      with:
        ruby-version: 3.3.0
        bundler-cache: true
        
    - name: Test CreateMLDemo
      run: bundle exec fastlane unit_test
    
